export { default as ArrowUpIcon } from '@/assets/icons/icon-arrow-up.svg'
export { default as ArrowDownIcon } from '@/assets/icons/icon-arrow-down.svg'
export { default as CalendarIcon } from '@/assets/icons/icon-calendar.svg'
export { default as CloseMenuIcon } from '@/assets/icons/icon-close-menu.svg'
export { default as MenuIcon } from '@/assets/icons/icon-menu.svg'
export { default as PlanningIcon } from '@/assets/icons/icon-planning.svg'
export { default as RemindersIcon } from '@/assets/icons/icon-reminders.svg'
export { default as TodoIcon } from '@/assets/icons/icon-todo.svg'
