export { default as ClientAudiophileImage } from '@/assets/images/client-audiophile.svg'
export { default as ClientDataBizImage } from '@/assets/images/client-databiz.svg'
export { default as ClientMakerImage } from '@/assets/images/client-maker.svg'
export { default as ClientMeetImage } from '@/assets/images/client-meet.svg'
export { default as LogoImage } from '@/assets/images/logo.svg'
export { default as HeroDesktopImage } from '@/assets/images/image-hero-desktop.png'
export { default as HeroMobileImage } from '@/assets/images/image-hero-mobile.png'
